name: phpsw-sculpin-demo
type: sculpin
language: php

flake:
  devshell:
    packages:
      - nodejs
      - php81
      - php81Packages.composer

git:
  ignore:
    - '!/assets/'
    - '/source/build/'

experimental:
  createInclusiveGitIgnoreFile: true
