name: 'PHPSW'
locale: en
talks:
  - title: Building Static Websites with PHP and Sculpin
    speaker: Oliver Davies
  - title: 'FPGA^2: An open-source FPGA'
    speaker: Robin Hodson
  - title: Introducing Domain Driven Design
    speaker: Rob Allen
  - title: Building Better TUIs (with PHP)
    speaker: Dan Leech
  - title: Thoughts on Ubiquitous Language
    speaker: Rob Allen
  - title: Testing Legacy
    speaker: Mike Karthauser
  - title: Building "Build Configs"
    speaker: Oliver Davies
  - title: Terraform from a dev’s perspective
    speaker: Nigel Dunn
  - title: What is TDD and why should I care?
    speaker: Naomi Gotts
  - title: Go for PHP
    speaker: Dan Leech
  - title: What's new in PHP 8.*
    speaker: Derick Rethans
  - title: Behaviour Driven Development (BDD) in Practice
    speaker: Ciaran McNulty
